// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Antal_magasiner")]
    public partial class AntalMagasiner
    {
        [Key]
        [Column("Lokation_ID")]
        public int LokationId { get; set; }
        [Column("Magasin_ID")]
        public int MagasinId { get; set; }
        [Column("Leveret_magasiner")]
        public int? LeveretMagasiner { get; set; }
        [Column("Afhentet_magasiner")]
        public int? AfhentetMagasiner { get; set; }

        [ForeignKey(nameof(LokationId))]
        [InverseProperty(nameof(Lokationer.AntalMagasiner))]
        public virtual Lokationer Lokation { get; set; }
    }
}