// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Contactperson")]
    public partial class Contactperson
    {
        [Column("Location_ID")]
        public int LocationId { get; set; }
        [Key]
        [Column("Contact_ID")]
        public int ContactId { get; set; }
        [Column("Contactperson")]
        [StringLength(40)]
        public string Contactperson1 { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(15)]
        public string Phone { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty(nameof(DistributionPoint.Contactpeople))]
        public virtual DistributionPoint Location { get; set; }
    }
}