// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Kontaktpersoner")]
    public partial class Kontaktpersoner
    {
        [Column("Lokation_ID")]
        public int LokationId { get; set; }
        [Key]
        [Column("Kontakt_ID")]
        public int KontaktId { get; set; }
        [Required]
        [StringLength(40)]
        public string Kontaktperson { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(15)]
        public string Telefonnummer { get; set; }

        [ForeignKey(nameof(LokationId))]
        [InverseProperty(nameof(Lokationer.Kontaktpersoners))]
        public virtual Lokationer Lokation { get; set; }
    }
}