// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Lokationer")]
    public partial class Lokationer
    {
        public Lokationer()
        {
            Kontaktpersoners = new HashSet<Kontaktpersoner>();
        }

        [Key]
        [Column("Lokation_ID")]
        public int LokationId { get; set; }
        [Required]
        [StringLength(30)]
        public string Firmanavn { get; set; }
        [Required]
        [StringLength(30)]
        public string Adresse { get; set; }
        public int Postnummer { get; set; }
        [StringLength(15)]
        public string Telefonnummer { get; set; }

        [InverseProperty("Lokation")]
        public virtual AntalMagasiner AntalMagasiner { get; set; }
        [InverseProperty("Lokation")]
        public virtual Åbningerstider Åbningerstider { get; set; }
        [InverseProperty(nameof(Kontaktpersoner.Lokation))]
        public virtual ICollection<Kontaktpersoner> Kontaktpersoners { get; set; }
    }
}