// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace MalgreTout.Models
{
    public partial class MalgretoutContext : DbContext
    {
        public MalgretoutContext()
        {
        }

        public MalgretoutContext(DbContextOptions<MalgretoutContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Contactperson> Contactpeople { get; set; }
        public virtual DbSet<DistributionPoint> DistributionPoints { get; set; }
        public virtual DbSet<NoOfMagazine> NoOfMagazines { get; set; }
        public virtual DbSet<OpeningHour> OpeningHours { get; set; }
        public virtual DbSet<Zipcode> Zipcodes { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=MalgreTout;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Contactperson>(entity =>
            {
                entity.HasKey(e => e.ContactId)
                    .HasName("PK__Contactp__82ACC1CD1FB62175");

                entity.Property(e => e.Contactperson1).IsUnicode(false);

                entity.Property(e => e.Email).IsUnicode(false);

                entity.Property(e => e.Phone).IsUnicode(false);

                entity.HasOne(d => d.Location)
                    .WithMany(p => p.Contactpeople)
                    .HasForeignKey(d => d.LocationId)
                    .HasConstraintName("FK__Contactpe__Locat__2E1BDC42");
            });

            modelBuilder.Entity<DistributionPoint>(entity =>
            {
                entity.HasKey(e => e.LocationId)
                    .HasName("PK__Distribu__D2BA00C238D66166");

                entity.Property(e => e.Address).IsUnicode(false);

                entity.Property(e => e.Company).IsUnicode(false);

                entity.HasOne(d => d.ZipcodeNavigation)
                    .WithMany(p => p.DistributionPoints)
                    .HasForeignKey(d => d.Zipcode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Distribut__Zipco__25869641");
            });

            modelBuilder.Entity<NoOfMagazine>(entity =>
            {
                entity.HasKey(e => e.MagasineId)
                    .HasName("PK__No_of_ma__3AD34079C80EAF5B");

                entity.HasOne(d => d.Location)
                    .WithMany(p => p.NoOfMagazines)
                    .HasForeignKey(d => d.LocationId)
                    .HasConstraintName("FK__No_of_mag__Locat__2B3F6F97");
            });

            modelBuilder.Entity<OpeningHour>(entity =>
            {
                entity.HasKey(e => e.OpeningId)
                    .HasName("PK__Opening___F48914FF48CA13B4");

                entity.Property(e => e.OpenHours).IsUnicode(false);

                entity.Property(e => e.WeekDay).IsUnicode(false);

                entity.HasOne(d => d.Location)
                    .WithMany(p => p.OpeningHours)
                    .HasForeignKey(d => d.LocationId)
                    .HasConstraintName("FK__Opening_h__Locat__286302EC");
            });

            modelBuilder.Entity<Zipcode>(entity =>
            {
                entity.HasKey(e => e.Zipcode1)
                    .HasName("PK__Zipcode__E546D6BFD837321B");

                entity.Property(e => e.Zipcode1).ValueGeneratedNever();

                entity.Property(e => e.City).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}