// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("No_of_magazine")]
    public partial class NoOfMagazine
    {
        [Key]
        [Column("Magasine_ID")]
        public int MagasineId { get; set; }
        [Column("Location_ID")]
        public int LocationId { get; set; }
        [Column("Magazine_issue")]
        public int? MagazineIssue { get; set; }
        [Column("Supplied_magazine")]
        public int? SuppliedMagazine { get; set; }
        [Column("Delivered_magazine")]
        public int? DeliveredMagazine { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty(nameof(DistributionPoint.NoOfMagazines))]
        public virtual DistributionPoint Location { get; set; }
    }
}