// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Opening_hour")]
    public partial class OpeningHour
    {
        [Key]
        [Column("Location_ID")]
        public int LocationId { get; set; }
        [Required]
        [Column("Opening_hour")]
        [StringLength(10)]
        public string OpeningHour1 { get; set; }

        [ForeignKey(nameof(LocationId))]
        [InverseProperty(nameof(DistributionPoint.OpeningHour))]
        public virtual DistributionPoint Location { get; set; }
    }
}