// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Zipcode")]
    public partial class Zipcode
    {
        public Zipcode()
        {
            DistributionPoints = new HashSet<DistributionPoint>();
        }

        [Key]
        [Column("Zipcode")]
        public int Zipcode1 { get; set; }
        [Required]
        [StringLength(30)]
        public string City { get; set; }

        [InverseProperty(nameof(DistributionPoint.ZipcodeNavigation))]
        public virtual ICollection<DistributionPoint> DistributionPoints { get; set; }
    }
}