// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MalgreTout.Models
{
    [Table("Åbningerstider")]
    public partial class Åbningerstider
    {
        [Key]
        [Column("Lokation_ID")]
        public int LokationId { get; set; }
        [Required]
        [StringLength(10)]
        public string Åbningstider { get; set; }

        [ForeignKey(nameof(LokationId))]
        [InverseProperty(nameof(Lokationer.Åbningerstider))]
        public virtual Lokationer Lokation { get; set; }
    }
}